name: Build and deploy TextCan Angular UI app to Azure static web app

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'TextCan_Web/**'
      - 'TextCan_React/**'
      - '.github/workflows/azure-static-web-ui.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        working-directory: ./TextCan_Web
        run: npm ci      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_DEPLOY_STATIC_WEB_UI_CREDENTIALS }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/TextCan_Web" # App source code path
          api_location: "" # No API functions in this project
          output_location: "dist/TextCan-Web" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
