name: Build and deploy key service Azure Function

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'KeyGenerationServiceServerless/**'
    - '.github/workflows/key_service_serverless.yml'
  pull_request:
    branches: [ master ]

env:
  AZURE_FUNCTIONAPP_NAME: 'func-keyservice-textcan-dev'
  AZURE_FUNCTIONAPP_ROOT_PATH: './KeyGenerationServiceServerless'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ${{ env.AZURE_FUNCTIONAPP_ROOT_PATH }}
      run: dotnet restore
    - name: Build
      working-directory: ${{ env.AZURE_FUNCTIONAPP_ROOT_PATH }}
      run: dotnet build --no-restore --configuration Release --output ./publish
    - name: Azure Login
      uses: azure/login@v2
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable
        creds: ${{ secrets.AZURE_DEPLOY_CREDENTIALS }}
    - name: Deploy
      uses: Azure/functions-action@v2
      with:
        # Name of the Azure Function App
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        # Path to package or folder. *.zip or a folder to deploy
        package: '${{ env.AZURE_FUNCTIONAPP_ROOT_PATH }}/publish'
