name: .NET

on:
  push:
    branches: [ master ]
    paths:
    - 'KeyGenerationServiceServerless/**'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./KeyGenerationServiceServerless
      run: dotnet restore
    - name: Build
      working-directory: ./KeyGenerationServiceServerless
      run: dotnet build --no-restore
      
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.4
      with:
        # Name of the Azure Function App
        app-name: 'func-keygen-textcan-dev'
        # Path to package or folder. *.zip or a folder to deploy
        package: 'KeyGenerationServiceServerless'
